scenario_name: town06_day_rain_high_traffic
camera:
  location:
    x: 290.2
    y: -18.7
    z: 8.15
  rotation:
    pitch: -24.95
    yaw: 1.96
    roll: 0.0
  image_width: 1280
  image_height: 720
  fov: 70
traffic_light:
  id: 111
weather:
  cloudiness: 40.0
  precipitation: 100.0
  sun_altitude_angle: 15.0
  fog_density: 10.0
  wetness: 50.0
simulation:
  total_frames: 5000
  capture_interval: 2
  warmup_frames: 100
  train_ratio: 0.8
  fixed_delta_seconds: 0.05
spawn:
  max_vehicles: 50
  spawn_radius: 100.0
  radius_center: camera
  spawn_points: ["33-81"]
  respawn_interval: 50
  despawn_distance: 100.0
  ratios:
    car: 15
    ambulance: 2
    bus: 2
    truck: 3
    police_car: 2
    fire_truck: 1
    bike: 4
output:
  directory: ./dataset_output
